name: Deploy to AWS ECR and App Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      APP_RUNNER_ARN: ${{ secrets.APP_RUNNER_ARN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Get commit SHA
      id: vars
      run: echo "COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Docker image
      run: |
        docker build -t $ECR_REPOSITORY:$COMMIT_SHA .

    - name: Push Docker image
      run: |
        docker push $ECR_REPOSITORY:$COMMIT_SHA

    - name: Update App Runner service to new image
      run: |
        cat <<EOF > update.json
        {
          "ImageRepository": {
            "ImageIdentifier": "${{ env.ECR_REPOSITORY }}:${{ env.COMMIT_SHA }}",
            "ImageRepositoryType": "ECR"
          }
        }
        EOF

        aws apprunner update-service \
          --service-arn ${{ env.APP_RUNNER_ARN }} \
          --source-configuration file://update.json
